# Env setup
env_id: "CarRacing-v3"

# Model sizes
hidden_state_dims: 200
latent_state_dims: [32, 32]
action_dims: 3
observation_dims: [64, 64]
encoder_filter_num_1: 32
encoder_filter_num_2: 64
encoder_hidden_layer_nodes: 200
decoder_filter_num_1: 32
decoder_filter_num_2: 64
decoder_hidden_layer_nodes: 200
dyn_pred_hidden_num_nodes_1: 200
dyn_pred_hidden_num_nodes_2: 200
rew_pred_hidden_num_nodes_1: 200
rew_pred_hidden_num_nodes_2: 200
cont_pred_hidden_num_nodes_1: 200
cont_pred_hidden_num_nodes_2: 200
hidden_layer_actor_1_size: 200
hidden_layer_actor_2_size: 200
hidden_layer_critic_1_size: 200
hidden_layer_critic_2_size: 200
device: 'cuda'

# Training Hyperparameters
horizon: 15
batch_size: 30
nu: 0.995
lambda_: 0.95
gamma: 0.99
buffer_size: 200000
sequence_length: 50
seed: 42
training_iterations: 20000
random_iterations: 1000
actor_lr: 0.00003
actor_betas: [0.9,0.999]
actor_eps: 0.0000001
critic_lr: 0.0001
critic_betas: [0.9,0.999]
critic_eps: 0.0000001
AC_epochs: 1
world_model_lr: 0.0001
world_model_betas: [0.9,0.999]
world_model_eps: 0.0000001
WM_epochs: 1
beta_prediction: 0.1
beta_dynamics: 0.5
beta_representation: 0.1
critic_reward_buckets: 255